#%RAML 1.0 DataType

type: object
properties:
  Hotel_ID: integer
  Guest_Name: string
  Age: integer
  Gender: string
  Check_In_Date: string
  Check_Out_Date: string
  Email: string
  Contact_No: string
  No_Of_Guest: integer